name: SabjiTaja
description: Buy vegetables ,fruits and meats online.



version: 1.0.0+5

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  list_tile_switch: ^1.0.0
  provider: ^6.0.2
  shared_preferences: ^2.0.12
  badges: ^2.0.2
  flutter_staggered_grid_view: ^0.6.1
  backdrop: ^0.7.1
  carousel_pro_nullsafety: ^1.0.2
  card_swiper: ^2.0.1
  cached_network_image: ^3.2.0
  wave: ^0.2.0
  image_picker: ^0.8.4+10
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  google_sign_in: ^5.4.3
  fluttertoast: ^8.0.9
  http: ^0.13.4
  sn_progress_dialog: ^1.0.3
  flutter_svg: ^1.0.3
  file_picker: ^5.2.5
  shimmer: ^2.0.0
  google_sign_in_web: ^0.10.1+2
  google_fonts: ^3.0.1
  connectivity_plus: ^3.0.2
  url_launcher: ^6.1.8
  url_strategy: ^0.2.0
  firebase_dynamic_links: ^5.0.11
  share_plus: ^6.3.0
  firebase_messaging: ^14.2.1
  loader_overlay: ^2.1.0
  intl: ^0.17.0
  firebase_crashlytics: ^3.0.12
  file: ^6.1.4





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.11.0"
  flutter_native_splash: ^2.2.16


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "dev_assets/sabjitaja_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "dev_assets/sabjitaja_logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "dev_assets/sabjitaja_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "dev_assets/sabjitaja_logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: "dev_assets/splash_img.png"
  color_dark: "#121212"
  image_dark: "dev_assets/splash_img.png"
  android_gravity: fill

  android_12:
    image: "dev_assets/splash_img.png"
    icon_background_color: "#ffffff"
    image_dark: "dev_assets/splash_img.png"
    icon_background_color_dark: "#121212"

  web: false

flutter:

  uses-material-design: true

  assets:
    - images/
    - icons/
